# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "8ff5c5140359530993c3193d218f7818"
name = "B2B AR Collections Assistant"
application_url = "https://shopify.dev/apps/default-app-home"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_orders,read_all_orders,read_payment_terms,read_customers"

[webhooks]
api_version = "2026-07"

  [[webhooks.subscriptions]]
  uri = "/webhooks/app/uninstalled"
  topics = [ "app/uninstalled" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/app/scopes_update"
  topics = [ "app/scopes_update" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/sync"
  topics = [ "orders/create", "orders/updated", "orders/paid", "orders/cancelled", "refunds/create", "order_transactions/create", "payment_schedules/due", "payment_terms/create", "payment_terms/update", "payment_terms/delete", "companies/create", "companies/update", "companies/delete", "company_locations/create", "company_locations/update", "company_locations/delete", "company_contacts/create", "company_contacts/update", "company_contacts/delete" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/customers/data_request"
  compliance_topics = [ "customers/data_request" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/customers/redact"
  compliance_topics = [ "customers/redact" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/shop/redact"
  compliance_topics = [ "shop/redact" ]

[auth]
redirect_urls = [ "https://shopify.dev/apps/default-app-home/api/auth" ]

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true
